---
title: "Executive Summary"
format: html
editor: visual
---

# Purpose
This analysis examines consumer shopping patterns from 3,900 transactions to identify opportunities for growth. By analyzing demographics, purchasing patterns, product preferences, and seasonal trends, this project uncovers ways to better marketing strategies and increase sales. This project combines data science techniques with marketing analytics to understand factors influencing consumer behavior.

# Dataset Description
Data Quality: Complete dataset with no missing values with 3,900 observations with 18 variables
Variable Types:
Categorical (11): Customer ID, Payment Method, Promo Code Used, Discount Applied, Shipping Type, Subscription Status, Season, Color, Size, Location, Category
Numeric (4): Age, Previous Purchases, Purchase Amount (USD), Review Rating
Additional (3): Gender, Item Purchased, Frequency of Purchases

# Key Findings
My analysis reveals three critical insights. Firstly, the 55+ age group generates the highest revenue, with subscription customers contributing more than non-subscribers. Second, Montana, California, and Idaho have the largest number of purchases and 68% of customers are male meaning that the female market is untapped. Third, customer satisfaction varies significantly by purchase frequency, with every-3-month shoppers rating highest (3.77) despite quarterly shoppers representing larger numbers but showing the lowest satisfaction. In addition, medium sizes were the most sold and XL and S were at the same level and maybe those sizes need more options. 

# Marketing Recommendations
As our objective is to increase customer sales and this dataset gives us insight as to how to not only increase sales and in some ways increase retention. A good way to increase revenue and sales is by targeting subscribers in states like Montana California and Idaho there will be a higher chance of sales increasing since these states have the highest amount of purchases from customers and those customers are more loyal. By targeting high purchasing loyal customers it becomes easier to maintain high retention rates and increase overall revenue. Creating loyalty programs rewarding every quartely would help increasing retention amongst that group and in turn increases product reviews which will postively impact companies and address quarterly purchasing customers directly. In addition, due to my other explorations on gender and its relationship with purchases and satisfaction, developing markets where female users can shop more for themselves and at times others might increase sales. The majority of purchasers were males based on this dataset so trying to tap into increasing the proportion of female shoppers may be beneficial. On a smaller level, addressing sizing and color issues and implementing more teal colors and medium size clothing may be beneficial. 
