---
title: "Progress Memo 1"
subtitle: |
  | Final Project
  | Data Science 1 with R (STAT 301-1)
author: "Sophie Langaigne"
date: "2025-10-26"
format:
  html:
    toc: true
    toc-depth: 3
    toc-location: left
    embed-resources: true
    link-external-newwindow: true

execute:
  warning: false
---

::: {.callout-tip icon=false}
## Github Repo Link
[Progress Memo Link](https://github.com/stat301-1-2025-fall/final-project-1-sophielangaigne2027-hash.git)
:::

## Data source

Shopping Datasets https://www.kaggle.com/datasets/ahmadrazakashif/shopping-behavior-dataset?resource=download^[This dataset is a shopping behavior dataset from Kaggle]

Kashif, A. R. (2023). Shopping Behavior Dataset. Kaggle. Retrieved October 26, 2025, from https://www.kaggle.com/datasets/ahmadrazakashif/shopping-behavior-dataset

## Why this data

I have chosen the Shopping Behavior Dataset from Kaggle because it offers a multifaceted view of individual consumer transactions, demographics, product details, frequency and promos. This dataset is perfect for marketing analytics which is something I'm very passionate about exploring. Understanding how certain factors can affect consumer behaviour. In addition, I'm currently working on a different dataset for my marketing classes and I wanted to combine my interests.

## Data quality & complexity check

This dataset has 3900 observations and 18 variables. The categorical variables are customer id, payment method, promo code used, discount applied, shipping type, subscription status, season, color, size, location and category. The numeric variables are age, previous purchases, purchase amount(USD) and review rating. The variables are complexed enough to do a solid data analysis. I would consider this dataset complete despite the No values for the promo code variable and this can be dealt with through filling in missing data values. In addition there are many unique values. Some variables may need to be referred to through string.

## Potential data issues

Potential Missingness: Some categorical nulls like Promo Code Used and Discount Applied may represent implicit "No"/"NA" values rather than true missing data. I replaced these with the mean. This dataset did not require a lot of tidying!

Dollar Amounts: High dollar amounts could not register in the dataset since there might be data entry limits with the website, there could be skewness in the data.

```{r}
#Load packages 
library(tidyverse)
library(dplyr)
library(readr)
library(naniar)
library(knitr)

#Read CSV file
shopping_dataset <- read.csv("data/raw/shopping_behavior_updated.csv")

vis_miss(shopping_dataset) +
  labs(title = "Missing Data Overview in Shopping Dataset") +
  theme_minimal()

```

## Misc

How can I make this better?